import { useEffect, useState } from "react";
import Image from "next/image";
import AuthLayout from "@/layout/AuthLayout";
import Listing from "@/pages/api/Listing";
import SeoFields from "@/common/SeoFields";
import toast from "react-hot-toast";

const empty = { name: "", designation: "", shortBio: "", bio: "", email: "", linkedinUrl: "", instagramUrl: "", displayOrder: 0, seoTitle: "", seoDescription: "", primaryKeyword: "", secondaryKeywords: "", image: null };

export default function HostAdmin() {
  const [hosts, setHosts] = useState([]); const [form, setForm] = useState(empty); const [editing, setEditing] = useState(null); const [loading, setLoading] = useState(false);
  const load = async () => { try { const response = await new Listing().AdminHostGet(); setHosts(Array.isArray(response?.data?.data) ? response.data.data : []); } catch { setHosts([]); } };
  useEffect(() => { load(); }, []);
  const change = (event) => { const { name, value, files } = event.target; setForm((current) => ({ ...current, [name]: files?.[0] || value })); };
  const edit = (host) => { setEditing(host); setForm({ ...empty, ...host, image: null }); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const submit = async (event) => { event.preventDefault(); setLoading(true); try { const payload = new FormData(); Object.entries(form).forEach(([key, value]) => { if (value !== null && value !== "") payload.append(key, value); }); const api = new Listing(); const response = editing ? await api.HostUpdate(editing.uuid, payload) : await api.HostAdd(payload); toast.success(response?.data?.message || "Host saved"); setForm(empty); setEditing(null); await load(); } catch (error) { toast.error(error?.response?.data?.message || "Host could not be saved until the database migration is applied"); } finally { setLoading(false); } };
  return <AuthLayout><div className="space-y-10 text-white"><div><h1 className="text-4xl font-extrabold">Host profiles</h1><p className="mt-2 text-white/60">Create profile pages and control the hosts available during episode upload.</p></div><form onSubmit={submit} className="grid gap-5 rounded-2xl border border-white/10 bg-[#111] p-6 md:grid-cols-2"><input name="name" value={form.name} onChange={change} placeholder="Host name" required className="rounded-lg border border-white/15 bg-black p-3"/><input name="designation" value={form.designation} onChange={change} placeholder="Designation" required className="rounded-lg border border-white/15 bg-black p-3"/><textarea name="shortBio" value={form.shortBio} onChange={change} placeholder="Short bio" required className="rounded-lg border border-white/15 bg-black p-3 md:col-span-2"/><textarea name="bio" value={form.bio} onChange={change} placeholder="Full profile content" rows="6" required className="rounded-lg border border-white/15 bg-black p-3 md:col-span-2"/><input name="linkedinUrl" value={form.linkedinUrl} onChange={change} placeholder="LinkedIn URL" className="rounded-lg border border-white/15 bg-black p-3"/><input name="instagramUrl" value={form.instagramUrl} onChange={change} placeholder="Instagram URL" className="rounded-lg border border-white/15 bg-black p-3"/><input type="number" name="displayOrder" value={form.displayOrder} onChange={change} placeholder="Display order" className="rounded-lg border border-white/15 bg-black p-3"/><input type="file" name="image" accept="image/*" onChange={change} required={!editing} className="rounded-lg border border-white/15 bg-black p-3"/><div className="md:col-span-2"><SeoFields formData={form} onChange={change}/></div><button disabled={loading} className="button-bg rounded-lg p-3 font-bold md:col-span-2">{loading ? "Saving..." : editing ? "Update host" : "Create host"}</button></form><div className="grid gap-5 md:grid-cols-3">{hosts.map((host) => <article key={host.slug} className="overflow-hidden rounded-2xl border border-white/10 bg-[#111]"><div className="relative aspect-square"><Image src={host.image} alt={host.name} fill sizes="33vw" className="object-cover"/></div><div className="p-5"><h2 className="text-2xl font-bold">{host.name}</h2><p className="mt-1 text-[#c99cff]">{host.designation}</p><button onClick={() => edit(host)} className="mt-5 rounded-lg border border-white/20 px-4 py-2">Edit profile</button></div></article>)}</div></div></AuthLayout>;
}
