import { useCallback, useEffect, useMemo, useState } from "react";
import AdminLayout from "@/components/layout/AdminLayout";
import PodcastApi from "@/services/podcastApi";
import { MdAdsClick, MdDevices, MdErrorOutline, MdOutlineRemoveRedEye, MdPeopleAlt, MdRefresh, MdSpeed, MdTimer } from "react-icons/md";
import { FaApple, FaSpotify, FaYoutube } from "react-icons/fa";

const PAGE_SIZE = 10;
const number = (value, digits = 0) => new Intl.NumberFormat("en-AU", { maximumFractionDigits: digits }).format(value || 0);
const duration = (seconds) => `${Math.floor((seconds || 0) / 60)}m ${Math.round((seconds || 0) % 60)}s`;
const percent = (value) => `${number((value || 0) * 100, 1)}%`;
const metric = (value) => value || "—";

function Panel({ title, subtitle, children, className = "" }) {
  return <article className={`rounded-2xl border border-violet-200 bg-white p-5 text-slate-900 shadow-sm ${className}`}><h3 className="font-bold text-slate-950">{title}</h3>{subtitle && <p className="mt-1 text-sm text-slate-600">{subtitle}</p>}<div className="mt-5">{children}</div></article>;
}
function Breakdown({ rows = [] }) {
  const max = Math.max(...rows.map((row) => row.value), 1);
  return <div className="space-y-3">{rows.length ? rows.map((row) => <div key={row.label}><div className="mb-1 flex justify-between gap-3 text-sm"><span className="truncate text-slate-700">{row.label}</span><b className="text-slate-950">{number(row.value)}</b></div><div className="h-1.5 overflow-hidden rounded-full bg-violet-100"><div className="h-full rounded-full bg-gradient-to-r from-fuchsia-600 to-purple-500" style={{ width: `${row.value / max * 100}%` }} /></div></div>) : <p className="text-sm text-slate-500">No data yet.</p>}</div>;
}
function Pager({ page, total, onChange }) {
  const pages = Math.max(1, Math.ceil(total / PAGE_SIZE));
  return <div className="mt-5 flex items-center justify-between border-t border-violet-100 pt-4 text-sm"><span className="text-slate-600">Page {page} of {pages} · {total} pages</span><div className="flex gap-2"><button disabled={page <= 1} onClick={() => onChange(page - 1)} className="rounded-lg border border-violet-300 px-3 py-2 font-semibold text-slate-800 disabled:opacity-40">Previous</button><button disabled={page >= pages} onClick={() => onChange(page + 1)} className="rounded-lg bg-violet-700 px-3 py-2 font-semibold text-white disabled:opacity-40">Next</button></div></div>;
}
function DataPager({ page, total, onChange, label = "rows" }) {
  const pages = Math.max(1, Math.ceil(total / PAGE_SIZE));
  return <div className="mt-5 flex items-center justify-between border-t border-violet-100 pt-4 text-sm"><span className="text-slate-600">Page {page} of {pages} · {total} {label}</span><div className="flex gap-2"><button disabled={page <= 1} onClick={() => onChange(page - 1)} className="rounded-lg border border-violet-300 px-3 py-2 font-semibold text-slate-800 disabled:opacity-40">Previous</button><button disabled={page >= pages} onClick={() => onChange(page + 1)} className="rounded-lg bg-violet-700 px-3 py-2 font-semibold text-white disabled:opacity-40">Next</button></div></div>;
}
function LineChart({ rows = [] }) {
  const values = rows.map((row) => row.views || 0); const max = Math.max(...values, 1); const points = values.map((value, index) => `${index / Math.max(values.length - 1, 1) * 100},${92 - value / max * 78}`).join(" ");
  return <Panel title="Views over time" subtitle="First-party page views"><div className="h-48">{rows.length ? <svg viewBox="0 0 100 100" preserveAspectRatio="none" className="h-full w-full" aria-label="Page views trend"><defs><linearGradient id="analyticsFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#9333ea" stopOpacity=".35" /><stop offset="1" stopColor="#9333ea" stopOpacity="0" /></linearGradient></defs><polygon points={`0,100 ${points} 100,100`} fill="url(#analyticsFill)" /><polyline points={points} fill="none" stroke="#8d2dcc" strokeWidth="2" vectorEffect="non-scaling-stroke" /></svg> : <p className="grid h-full place-items-center text-slate-500">Data appears after public visits.</p>}</div></Panel>;
}
function StatusBadge({ online, status }) { return <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-bold ${online ? "bg-emerald-100 text-emerald-800" : "bg-red-100 text-red-800"}`}>{online ? `Online · ${status}` : status ? `Error · ${status}` : "Offline"}</span>; }

export default function AnalyticsPage() {
  const [analytics, setAnalytics] = useState(null); const [range, setRange] = useState("28daysAgo"); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const [pages, setPages] = useState([]); const [strategy, setStrategy] = useState("mobile"); const [audits, setAudits] = useState({}); const [auditLoading, setAuditLoading] = useState(false);
  const [speedPage, setSpeedPage] = useState(1); const [topPage, setTopPage] = useState(1); const [healthPage, setHealthPage] = useState(1); const [health, setHealth] = useState(null); const [healthLoading, setHealthLoading] = useState(false);
  const [sourcePage, setSourcePage] = useState(1); const [conversionPage, setConversionPage] = useState(1); const [sourceFilter, setSourceFilter] = useState("all");
  const api = useMemo(() => new PodcastApi(), []);
  const loadAnalytics = useCallback(async () => { setLoading(true); setError(""); try { const response = await api.analyticsGet({ startDate: range }); setAnalytics(response?.data?.data?.analytics || null); } catch (err) { setError(err?.response?.data?.message || err.message); } finally { setLoading(false); } }, [api, range]);
  const loadHealth = useCallback(async () => { setHealthLoading(true); try { const response = await api.analyticsHealth(); setHealth(response?.data?.data || null); } catch (err) { setError(err?.response?.data?.message || err.message); } finally { setHealthLoading(false); } }, [api]);
  useEffect(() => { loadAnalytics(); }, [loadAnalytics]);
  useEffect(() => { api.analyticsPageSpeedPages().then((response) => setPages(response?.data?.data?.pages || [])).catch((err) => setError(err?.response?.data?.message || err.message)); loadHealth(); }, [api, loadHealth]);

  const speedRows = useMemo(() => pages.slice((speedPage - 1) * PAGE_SIZE, speedPage * PAGE_SIZE), [pages, speedPage]);
  const auditVisible = useCallback(async (force = false) => {
    if (!speedRows.length) return;
    const pending = speedRows.filter((page) => force || !audits[`${page.url}:${strategy}`]);
    if (!pending.length) return;
    setAuditLoading(true);
    for (const page of pending) {
      const key = `${page.url}:${strategy}`;
      try { const response = await api.analyticsPageSpeed({ url: page.url, strategy }); setAudits((current) => ({ ...current, [key]: response?.data?.data?.pageSpeed })); }
      catch (err) { setAudits((current) => ({ ...current, [key]: { error: err?.response?.data?.message || err.message } })); }
    }
    setAuditLoading(false);
  }, [api, audits, speedRows, strategy]);
  useEffect(() => { auditVisible(); }, [speedPage, strategy, pages.length]); // PageSpeed only; traffic analytics remains untouched.

  const allTopPages = useMemo(() => {
    const measured = new Map((analytics?.pages || []).map((row) => [row.path, row]));
    return pages.map((page) => ({ ...page, ...(measured.get(page.path) || { views: 0, visitors: 0, sessions: 0, averageEngagement: 0 }) })).sort((a, b) => b.views - a.views);
  }, [analytics, pages]);
  const topRows = allTopPages.slice((topPage - 1) * PAGE_SIZE, topPage * PAGE_SIZE);
  const sourceOptions = useMemo(() => [...new Set((analytics?.sourcePages || []).map((row) => row.source))].sort(), [analytics]);
  const sourcePageRows = useMemo(() => (analytics?.sourcePages || []).filter((row) => sourceFilter === "all" || row.source === sourceFilter), [analytics, sourceFilter]);
  const visibleSourceRows = sourcePageRows.slice((sourcePage - 1) * PAGE_SIZE, sourcePage * PAGE_SIZE);
  const conversionRows = analytics?.platformConversions || [];
  const visibleConversionRows = conversionRows.slice((conversionPage - 1) * PAGE_SIZE, conversionPage * PAGE_SIZE);
  const healthRows = (health?.pages || []).slice((healthPage - 1) * PAGE_SIZE, healthPage * PAGE_SIZE);
  const cards = [["Visitors", number(analytics?.summary?.visitors), MdPeopleAlt], ["Page views", number(analytics?.summary?.pageViews), MdOutlineRemoveRedEye], ["Sessions", number(analytics?.summary?.sessions), MdSpeed], ["Avg. engagement", duration(analytics?.summary?.averageEngagement), MdTimer], ["Pages / session", number(analytics?.summary?.pagesPerSession, 2), MdDevices], ["Bounce rate", percent(analytics?.summary?.bounceRate), MdAdsClick]];

  return <AdminLayout><div className="space-y-7 text-slate-900">
    <header className="flex flex-wrap items-end justify-between gap-4 border-b border-violet-200 pb-5"><div><p className="text-sm font-bold uppercase tracking-[.18em] text-violet-700">Website intelligence</p><h1 className="mt-1 text-3xl font-black text-slate-950 md:text-4xl">Analytics & health centre</h1><p className="mt-2 text-slate-600">First-party traffic, real-user errors, uptime and PageSpeed for every public URL.</p></div><div className="flex flex-wrap gap-2"><select value={range} onChange={(event) => setRange(event.target.value)} className="rounded-xl border border-violet-300 bg-white px-4 py-3 text-slate-900"><option value="7daysAgo">Last 7 days</option><option value="28daysAgo">Last 28 days</option><option value="90daysAgo">Last 90 days</option></select><button onClick={loadAnalytics} className="inline-flex items-center gap-2 rounded-xl bg-violet-700 px-5 py-3 font-bold text-white"><MdRefresh />Refresh traffic</button></div></header>
    {error && <div className="rounded-xl border border-red-300 bg-red-50 p-4 text-red-800">{error}</div>}
    {loading ? <div className="grid min-h-80 place-items-center text-slate-600">Loading first-party analytics…</div> : <>
      <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-6">{cards.map(([label, value, Icon]) => <article key={label} className="rounded-2xl border border-violet-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><span className="text-slate-600">{label}</span><Icon className="text-violet-700" size={23} /></div><strong className="mt-4 block text-3xl text-slate-950">{value}</strong></article>)}</section>
      <section className="grid gap-5 xl:grid-cols-[1.55fr_.85fr]"><LineChart rows={analytics?.trend} /><Panel title="Live now" subtitle="Active sessions in the last 30 minutes"><strong className="mb-5 block text-5xl text-emerald-700">{number(analytics?.realtime?.visitors)}</strong><Breakdown rows={analytics?.realtime?.pages} /></Panel></section>
      <Panel title="All pages" subtitle="Views, visitors and engagement by URL"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead className="text-left uppercase text-slate-500"><tr><th className="pb-3">Page name</th><th>Views</th><th>Visitors</th><th>Sessions</th><th>Avg. engagement</th></tr></thead><tbody>{topRows.map((row) => <tr key={row.path} className="border-t border-violet-100"><td className="max-w-md py-3 pr-4"><b className="block text-slate-950">{row.title || row.label}</b><small className="text-slate-500">{row.path}</small></td><td>{number(row.views)}</td><td>{number(row.visitors)}</td><td>{number(row.sessions)}</td><td>{duration(row.averageEngagement)}</td></tr>)}</tbody></table></div><Pager page={topPage} total={allTopPages.length} onChange={setTopPage} /></Panel>
      <Panel title="Traffic attribution by page" subtitle="UTM sources such as email, LinkedIn and Instagram, broken down by the page people visited.">
        <div className="mb-4 flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-slate-600">Use <b>utm_source</b>, <b>utm_medium</b> and <b>utm_campaign</b> on shared links for reliable attribution.</p><select value={sourceFilter} onChange={(event) => { setSourceFilter(event.target.value); setSourcePage(1); }} className="rounded-xl border border-violet-300 bg-white px-4 py-2 text-slate-900"><option value="all">All sources</option>{sourceOptions.map((source) => <option key={source} value={source}>{source}</option>)}</select></div>
        <div className="overflow-x-auto"><table className="w-full min-w-[1040px] text-sm"><thead className="text-left uppercase text-slate-500"><tr><th className="pb-3">Source</th><th>Medium</th><th>Campaign</th><th>Landing / viewed page</th><th>Page views</th><th>Visitors</th><th>Total engaged time</th><th>Avg. engagement</th></tr></thead><tbody>{visibleSourceRows.map((row, index) => <tr key={`${row.source}-${row.path}-${index}`} className="border-t border-violet-100"><td className="py-3 pr-3"><span className="inline-flex rounded-full bg-violet-100 px-3 py-1 font-bold text-violet-800">{row.source}</span></td><td>{row.medium}</td><td>{row.campaign}</td><td className="max-w-sm pr-4"><b className="block text-slate-950">{row.title || row.path}</b><small className="text-slate-500">{row.path}</small></td><td>{number(row.pageViews)}</td><td>{number(row.visitors)}</td><td>{duration(row.totalEngagementSeconds)}</td><td>{duration(row.averageEngagementSeconds)}</td></tr>)}</tbody></table>{!visibleSourceRows.length && <p className="py-8 text-center text-slate-500">Attributed traffic will appear after someone opens a UTM-tagged link.</p>}</div><DataPager page={sourcePage} total={sourcePageRows.length} onChange={setSourcePage} label="source/page rows" />
      </Panel>
      <section className="grid gap-5 xl:grid-cols-[1.3fr_.7fr]"><Panel title="Platform conversions" subtitle="Outbound visits from your website"><div className="grid gap-3 sm:grid-cols-3">{[["YouTube", analytics?.platforms?.youtube, FaYoutube, "#e11d48"], ["Spotify", analytics?.platforms?.spotify, FaSpotify, "#15803d"], ["Apple Podcasts", analytics?.platforms?.apple, FaApple, "#7e22ce"]].map(([label, value, Icon, colour]) => <div key={label} className="flex items-center gap-4 rounded-xl border border-violet-200 bg-violet-50 p-4"><Icon size={25} style={{ color: colour }} /><span className="flex-1 text-slate-800">{label}</span><b className="text-xl text-slate-950">{number(value)}</b></div>)}</div></Panel><Panel title="Real-user errors" subtitle="JavaScript and resource failures reported by visitors"><strong className={`text-4xl ${analytics?.errors?.total ? "text-red-700" : "text-emerald-700"}`}>{number(analytics?.errors?.total)}</strong><p className="mt-2 text-sm text-slate-600">{analytics?.errors?.total ? "Review recent errors in Website health below." : "No browser errors in this date range."}</p></Panel></section>
      <Panel title="Platform redirects by originating page" subtitle="Every click to YouTube, Spotify or Apple Podcasts, including the website page and attributed traffic source."><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-sm"><thead className="text-left uppercase text-slate-500"><tr><th className="pb-3">Platform</th><th>Originating page</th><th>Traffic source</th><th>Clicks</th><th>Unique visitors</th></tr></thead><tbody>{visibleConversionRows.map((row, index) => <tr key={`${row.platform}-${row.path}-${row.source}-${index}`} className="border-t border-violet-100"><td className="py-3 font-bold text-slate-950">{row.platform}</td><td className="max-w-md pr-4 text-slate-700">{row.path}</td><td><span className="rounded-full bg-violet-100 px-3 py-1 font-semibold text-violet-800">{row.source}</span></td><td>{number(row.clicks)}</td><td>{number(row.visitors)}</td></tr>)}</tbody></table>{!visibleConversionRows.length && <p className="py-8 text-center text-slate-500">Platform click details will appear after visitors use an external podcast link.</p>}</div><DataPager page={conversionPage} total={conversionRows.length} onChange={setConversionPage} label="conversion rows" /></Panel>
      <section className="grid gap-5 md:grid-cols-2 xl:grid-cols-4"><Panel title="Traffic sources"><Breakdown rows={analytics?.sources} /></Panel><Panel title="Referring websites"><Breakdown rows={analytics?.referrers} /></Panel><Panel title="Devices"><Breakdown rows={analytics?.devices} /></Panel><Panel title="Browsers"><Breakdown rows={analytics?.browsers} /></Panel><Panel title="Operating systems"><Breakdown rows={analytics?.operatingSystems} /></Panel><Panel title="Countries"><Breakdown rows={analytics?.countries} /></Panel><Panel title="Campaigns"><Breakdown rows={analytics?.campaigns} /></Panel><Panel title="Recorded events"><Breakdown rows={analytics?.events} /></Panel></section>
      <section className="grid gap-5 xl:grid-cols-2"><Panel title="Scroll depth"><Breakdown rows={Object.entries(analytics?.scrollDepth || {}).map(([label, value]) => ({ label: `${label}%`, value }))} /></Panel><Panel title="Real-user Web Vitals" subtitle="75th percentile from actual visitors"><div className="grid grid-cols-2 gap-3 sm:grid-cols-5">{["LCP", "INP", "CLS", "FCP", "TTFB"].map((name) => <div key={name} className="rounded-xl border border-violet-200 bg-violet-50 p-4"><span className="text-slate-600">{name}</span><b className="mt-2 block text-xl text-slate-950">{analytics?.webVitals?.[name]?.p75 == null ? "—" : number(analytics.webVitals[name].p75, 2)}</b><small className="text-slate-500">{number(analytics?.webVitals?.[name]?.samples)} samples</small></div>)}</div></Panel></section>
    </>}

    <Panel title="PageSpeed Insights — all public pages" subtitle="Ten URLs per page. Changing Mobile/Desktop only loads this table and never refreshes traffic analytics."><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div className="flex rounded-xl border border-violet-300 bg-violet-50 p-1">{["mobile", "desktop"].map((item) => <button key={item} onClick={() => setStrategy(item)} className={`rounded-lg px-4 py-2 font-semibold capitalize ${strategy === item ? "bg-violet-700 text-white" : "text-slate-700"}`}>{item}</button>)}</div><button disabled={auditLoading} onClick={() => auditVisible(true)} className="inline-flex items-center gap-2 rounded-xl border border-violet-400 px-4 py-2 font-bold text-violet-800 disabled:opacity-50"><MdRefresh />{auditLoading ? "Auditing pages…" : "Refresh these 10 pages"}</button></div><div className="overflow-x-auto"><table className="w-full min-w-[1180px] text-sm"><thead className="text-left uppercase text-slate-500"><tr><th className="pb-3">Page name</th><th>Performance</th><th>Accessibility</th><th>Best practices</th><th>SEO</th><th>LCP</th><th>INP</th><th>FCP</th><th>CLS</th><th>TTFB</th></tr></thead><tbody>{speedRows.map((page) => { const result = audits[`${page.url}:${strategy}`]; return <tr key={page.url} className="border-t border-violet-100"><td className="max-w-xs py-4 pr-4"><b className="block text-slate-950">{page.label}</b><small className="text-slate-500">{page.path}</small>{result?.error && <small className="mt-1 block text-red-700">{result.error}</small>}</td><td>{result?.scores?.performance ?? "…"}</td><td>{result?.scores?.accessibility ?? "…"}</td><td>{result?.scores?.["best-practices"] ?? "…"}</td><td>{result?.scores?.seo ?? "…"}</td><td>{metric(result?.metrics?.lcp)}</td><td>{metric(result?.metrics?.inp)}</td><td>{metric(result?.metrics?.fcp)}</td><td>{metric(result?.metrics?.cls)}</td><td>{metric(result?.metrics?.ttfb)}</td></tr>; })}</tbody></table></div><Pager page={speedPage} total={pages.length} onChange={setSpeedPage} /></Panel>

    <Panel title="Website health & errors" subtitle="Every public URL is checked server-side. Results cache for five minutes; browser errors come from real visitors."><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div className="flex gap-3"><span className="rounded-lg bg-emerald-100 px-3 py-2 font-bold text-emerald-800">Online {health?.summary?.online || 0}</span><span className="rounded-lg bg-red-100 px-3 py-2 font-bold text-red-800">Failing {health?.summary?.failing || 0}</span></div><button disabled={healthLoading} onClick={loadHealth} className="inline-flex items-center gap-2 rounded-xl bg-violet-700 px-4 py-2 font-bold text-white disabled:opacity-50"><MdRefresh />{healthLoading ? "Checking…" : "Check all pages"}</button></div><div className="overflow-x-auto"><table className="w-full min-w-[820px] text-sm"><thead className="text-left uppercase text-slate-500"><tr><th className="pb-3">Page</th><th>Status</th><th>Response time</th><th>Last checked</th><th>Error</th></tr></thead><tbody>{healthRows.map((row) => <tr key={row.url} className="border-t border-violet-100"><td className="max-w-md py-3 pr-4"><b className="block text-slate-950">{row.label}</b><small className="text-slate-500">{row.path}</small></td><td><StatusBadge online={row.online} status={row.status} /></td><td>{number(row.responseTime)} ms</td><td>{row.checkedAt ? new Date(row.checkedAt).toLocaleString("en-AU") : "—"}</td><td className="text-red-700">{row.error || "—"}</td></tr>)}</tbody></table></div><Pager page={healthPage} total={health?.pages?.length || 0} onChange={setHealthPage} />
      {(analytics?.errors?.recent || []).length > 0 && <div className="mt-7"><h4 className="flex items-center gap-2 font-bold text-slate-950"><MdErrorOutline className="text-red-700" />Recent visitor errors</h4><div className="mt-3 max-h-80 space-y-2 overflow-auto">{analytics.errors.recent.map((item, index) => <div key={`${item.createdAt}-${index}`} className="rounded-xl border border-red-200 bg-red-50 p-3"><div className="flex flex-wrap justify-between gap-2"><b className="text-red-900">{item.message}</b><time className="text-xs text-slate-500">{new Date(item.createdAt).toLocaleString("en-AU")}</time></div><p className="mt-1 text-sm text-slate-700">{item.path}{item.source ? ` · ${item.source}` : ""}</p></div>)}</div></div>}
    </Panel>
  </div></AdminLayout>;
}
